### ISSUE TITLE
The setSingleData in Body class does not accept 0 as value

### ISSUE THREAD

**Issue by pengyue** [madkom/Pact-PHP-Client#1]
```
private function setSingleData($key, $value)
    {
        if (!$key || !$value) {
            throw new PactException("Key and values should'nt be empty");
        }

        $this->data[$key] = $value;
    }
```

$value is 0, !$value will return true, it could be !isset($value) ?

**Comment by brzuchal** [comment]
Both arguments are required, although `$value` could be also 0 or false - should be validated against being not `null`. Invoking `!isset($value)` won't never happen because `$value` parameter is required and cannot by bypassed in method call.
@dgafka I think we can replace negation with `!is_null($value)` or `null === $value` check, correct me if am wrong.

**Comment by pengyue** [comment]
if $value = 0, `!$key || !is_null($value)` will still lead to the exception, isn't it? @brzuchal

**Comment by dgafka** [comment]
Values that shouldn't be used are null and empty string. 
So validation, that we can check against could be:
is_null($value) || $value = ''

**Comment by dgafka** [comment]
fixed, ver. `0.8.2`

**Comment by pengyue** [comment]
@dgafka Thanks for fixing it, I have one question on this fix, I understand the `$key` could not be `null` or `''`, any reason why the `$value` could not be `null` or `''`?

**Comment by dgafka** [comment]
@pengyue tbh I don't remember why I've made such constraint. Probably it was creating some issues, but I am not sure of that.

**Comment by pengyue** [comment]
Thanks for reply @dgafka , for example, this is my response in `willRespondWith`, the `category` and `description` could be `null` or `''`, any suggestions?     



`"body"          => [
                    "cashback_amount"           => 1.34,
                    "created"                   => "2017-03-16T23:06:34+00:00",
                    "currency"                  => "GBP",
                    "customer_order_reference"  => "ORD-20170316-230634-332CF15B",
                    "domain"                    => 1,
                    "order_number"              => "332CF15B",
                    "payment_token"             => "PENDING-ID",
                    "products"  => [
                        [
                            "cashback_percentage"   => 0.54,
                            "category"              => null,
                            "product_id"            => "45987463",
                            "image"                 => "https://images.weflubit.com/c/180/180/11098960-e02d-5de8-86bb-9678eb0f6794-original.jpg",
                            "price"                 => 5.36,
                            "quantity"              => 1,
                            "seller"                => "Glitterstore",
                            "seller_id"             => "7af660ba-0340-416f-abe0-50b4125a3c13",
                            "shipping_info"         => "Yodel - 48 hour (3-5 working days)",
                            "shipping_method"       => 21991,
                            "shipping_price"        => 1.13,
                            "sku"                   => "5ERWJ8OJWY",
                            "title"                 => "ORANGE 11 - Semi Permanent Tattoo Pen Stargazer 1ml",
                            "description"   => ""
                        ],
                    ],
                    "quantity"      => 1,
                    "status"        => [
                        "display_name"  => "Pending",
                        "display_order" => 1,
                        "is_public"     => false,
                        "status_name"   => 'DRAFT',
                    ],
                    "tax_amount"            => 0,
                    "total"                 => 6.49,
                    "total_in_pence"        => 649,
                    "total_shipping_cost"   => 1.13,
                    "user"                  => "6469475",
                ]`

**Comment by dgafka** [comment]
You may try `\Madkom\PactClient\Application\Pact::like('')`
https://github.com/madkom/Pact-PHP-Client/blob/master/usage/modifiers-interaction.php

**Comment by pengyue** [comment]
That works! I need to look into PACT docs more  👍 :1st_place_medal: @dgafka

**Comment by dgafka** [comment]
@pengyue glad to hear :)
